
INSERT INTO `phpraid_config` VALUES ('admin_email','webmaster@yourdomain.com');
INSERT INTO `phpraid_config` VALUES ('anon_view', '1');
INSERT INTO `phpraid_config` VALUES ('auto_queue','0');
INSERT INTO `phpraid_config` VALUES ('date_format','m/d/Y');
INSERT INTO `phpraid_config` VALUES ('debug','0');
INSERT INTO `phpraid_config` VALUES ('default_group','nil');
INSERT INTO `phpraid_config` VALUES ('disable','0');
INSERT INTO `phpraid_config` VALUES ('disable_freeze','0');
INSERT INTO `phpraid_config` VALUES ('dst','0');
INSERT INTO `phpraid_config` VALUES ('email_signature','Thanks');
INSERT INTO `phpraid_config` VALUES ('faction','alliance');
INSERT INTO `phpraid_config` VALUES ('guild_description','raid management made easy');
INSERT INTO `phpraid_config` VALUES ('guild_name','WoW Raid Manager');
INSERT INTO `phpraid_config` VALUES ('guild_server','Illidan');
INSERT INTO `phpraid_config` VALUES ('header_link','http://www.yourdomain.com/');
INSERT INTO `phpraid_config` VALUES ('header_logo','templates/SpiffyJr/images/logo_phpRaid.jpg');
INSERT INTO `phpraid_config` VALUES ('language','english');
INSERT INTO `phpraid_config` VALUES ('multiple_signups','0');
INSERT INTO `phpraid_config` VALUES ('phpraid_addon_link','http://www.wowraidmanager.net');
INSERT INTO `phpraid_config` VALUES ('armory_link','http://www.wowarmory.com');
INSERT INTO `phpraid_config` VALUES ('armory_language','en');
INSERT INTO `phpraid_config` VALUES ('register_url','register.php');
INSERT INTO `phpraid_config` VALUES ('roster_integration','0');
INSERT INTO `phpraid_config` VALUES ('show_id','0');
INSERT INTO `phpraid_config` VALUES ('showphpraid_addon','1');
INSERT INTO `phpraid_config` VALUES ('template','SpiffyJr');
INSERT INTO `phpraid_config` VALUES ('time_format','h:i a');
INSERT INTO `phpraid_config` VALUES ('timezone','-0600');
INSERT INTO `phpraid_config` VALUES ('resop', '0');
INSERT INTO `phpraid_config` VALUES ('enable_five_man', '0');
INSERT INTO `phpraid_config` VALUES ('user_queue_promote', '0');
INSERT INTO `phpraid_config` VALUES ('user_queue_comments', '1');
INSERT INTO `phpraid_config` VALUES ('user_queue_cancel', '1');
INSERT INTO `phpraid_config` VALUES ('user_queue_delete', '1');
INSERT INTO `phpraid_config` VALUES ('user_cancel_queue', '1');
INSERT INTO `phpraid_config` VALUES ('user_cancel_promote', '0');
INSERT INTO `phpraid_config` VALUES ('user_cancel_comments', '1');
INSERT INTO `phpraid_config` VALUES ('user_cancel_delete', '0');
INSERT INTO `phpraid_config` VALUES ('user_drafted_queue', '1');
INSERT INTO `phpraid_config` VALUES ('user_drafted_comments', '1');
INSERT INTO `phpraid_config` VALUES ('user_drafted_cancel', '1');
INSERT INTO `phpraid_config` VALUES ('user_drafted_delete', '0');
INSERT INTO `phpraid_config` VALUES ('rl_queue_promote', '1');
INSERT INTO `phpraid_config` VALUES ('rl_queue_comments', '1');
INSERT INTO `phpraid_config` VALUES ('rl_queue_cancel', '0');
INSERT INTO `phpraid_config` VALUES ('rl_queue_delete', '0');
INSERT INTO `phpraid_config` VALUES ('rl_cancel_queue', '0');
INSERT INTO `phpraid_config` VALUES ('rl_cancel_promote', '0');
INSERT INTO `phpraid_config` VALUES ('rl_cancel_comments', '1');
INSERT INTO `phpraid_config` VALUES ('rl_cancel_delete', '1');
INSERT INTO `phpraid_config` VALUES ('rl_drafted_queue', '1');
INSERT INTO `phpraid_config` VALUES ('rl_drafted_comments', '1');
INSERT INTO `phpraid_config` VALUES ('rl_drafted_cancel', '0');
INSERT INTO `phpraid_config` VALUES ('rl_drafted_delete', '0');
INSERT INTO `phpraid_config` VALUES ('admin_queue_promote', '1');
INSERT INTO `phpraid_config` VALUES ('admin_queue_comments', '1');
INSERT INTO `phpraid_config` VALUES ('admin_queue_cancel', '0');
INSERT INTO `phpraid_config` VALUES ('admin_queue_delete', '0');
INSERT INTO `phpraid_config` VALUES ('admin_cancel_queue', '0');
INSERT INTO `phpraid_config` VALUES ('admin_cancel_promote', '0');
INSERT INTO `phpraid_config` VALUES ('admin_cancel_comments', '1');
INSERT INTO `phpraid_config` VALUES ('admin_cancel_delete', '1');
INSERT INTO `phpraid_config` VALUES ('admin_drafted_queue', '1');
INSERT INTO `phpraid_config` VALUES ('admin_drafted_comments', '1');
INSERT INTO `phpraid_config` VALUES ('admin_drafted_cancel', '0');
INSERT INTO `phpraid_config` VALUES ('admin_drafted_delete', '0');
INSERT INTO `phpraid_config` VALUES ('rss_site_url', 'http://localhost/phpraid');
INSERT INTO `phpraid_config` VALUES ('rss_export_url', 'http://localhost/phpraid');
INSERT INTO `phpraid_config` VALUES ('rss_feed_amt', '5');
INSERT INTO `phpraid_config` VALUES ('armory_link','http://www.wowarmory.com');
INSERT INTO `phpraid_config` VALUES ('armory_language','en');
INSERT INTO `phpraid_config` VALUES ('role1_name','tank');
INSERT INTO `phpraid_config` VALUES ('role2_name','melee');
INSERT INTO `phpraid_config` VALUES ('role3_name','healer');
INSERT INTO `phpraid_config` VALUES ('role4_name','ranged');
INSERT INTO `phpraid_config` VALUES ('role5_name','misc1');
INSERT INTO `phpraid_config` VALUES ('role6_name','misc2');
INSERT INTO `phpraid_config` VALUES ('enforce_role_limits', '1');
INSERT INTO `phpraid_config` VALUES ('enforce_class_limits', '0');
INSERT INTO `phpraid_config` VALUES ('class_as_min', '1');
INSERT INTO `phpraid_config` VALUES ('enable_armory', '1');
INSERT INTO `phpraid_config` VALUES ('enable_eqdkp', '0');
INSERT INTO `phpraid_config` VALUES ('eqdkp_url', 'http://localhost/eqdkp');
INSERT INTO `phpraid_config` VALUES ('ampm', '12');
INSERT INTO `phpraid_config` VALUES ('raid_view_type','by_class');

INSERT INTO `phpraid_permissions` (`name`,`description`,`announcements`,`configuration`,`guilds`,`locations`,`permissions`,`profile`,`raids`,`logs`,`users`) VALUES ('WRM Superadmin','Full access','1','1','1','1','1','1','1','1','1');

INSERT INTO `phpraid_version` VALUES ('3.0.9.2','Version 3.0.9.2 of phpRaid');
INSERT INTO `phpraid_version` VALUES ('3.1.0','Version 3.1.0 of phpRaid (Beta)');
INSERT INTO `phpraid_version` VALUES ('3.1.1','Version 3.1.1 of phpRaid');
INSERT INTO `phpraid_version` VALUES ('3.1.2','Version 3.1.2 of WoW Raid Manager');
INSERT INTO `phpraid_version` VALUES ('3.2.0','Version 3.2.0 of WoW Raid Manager');
INSERT INTO `phpraid_version` VALUES ('3.2.1','Version 3.2.1 of WoW Raid Manager');
INSERT INTO `phpraid_version` VALUES ('3.5.0','Version 3.5.0 of WoW Raid Manager');